### ISSUE TITLE
BigQuery TypeError: connect() got an unexpected keyword argument 'database'

### ISSUE THREAD

**Issue by dougscc** [visidata/vdsql#21]
I installed using
```pip install ibis-framework[bigquery] vdsql```
on  python 3.8.

Connecting with `vdsql bigquery:///my-project-name` resulted in a listing of all the datasets within the project. So far so go.

Upon highlighting a dataset, I got the error:

```TypeError: connect() got an unexpected keyword argument 'database'```

... which I am not going to guess at, since I've never actually used `vdsql` before, and really don't know how to enable debugging.

Is there a specific version of `ibis-framework` I should be forcing?

**Comment by anjakefala** [comment]
@dougscc Yes! 

This should work with `ibis-framework` 3.2.0. If you are still having trouble with that, I would update to the `develop` version of https://github.com/ibis-project/ibis

`pip install git+https://github.com/ibis-project/ibis.git`. I am having trouble finding the precise version of `ibis-framework` where this API change happened.

I am going to try to reproduce. If you end up trying a precise version, and it solves the problem, could you please report back?

**Comment by dougscc** [comment]
Attempted a full re-install and got:

` WARNING: ibis-framework 3.2.0 does not provide the extra 'bigquery'` which is unfortunate.

Is the bigquery extension gone?

**Comment by lxcode** [comment]
@dougscc You need to install ibis-bigquery separately:

https://github.com/ibis-project/ibis-bigquery
